### ISSUE TITLE
Explain in the README how this code leverages IATI Data Dump

### ISSUE THREAD

**Issue by jpmckinney** [andylolz/iati-canary#6]
I see that the Dropbox metadata.json file is updated by a Heroku deployment of https://github.com/andylolz/iati-data-dump, but what generates the gist?

**Comment by andylolz** [comment]
Which gist? Do you mean this gist?
https://gist.github.com/andylolz/8a4e0657ec14c999de6f70f339656852

It’s generated / updated here: https://github.com/andylolz/iati-data-dump/blob/8b51bd4f91322630aa3e1c5448d732fc07804c36/run.sh#L37-L39

**Comment by andylolz** [comment]
I’ve added some comments to the code to document this: 4b39f74974e571bc7b780ffa4d9ae2426de89fcf

These are still a bit magical, so I may try to explain elsewhere how this works. Does that sound like a worthwhile endeavour?

**Comment by jpmckinney** [comment]
The comments help me sufficiently to understand the implementation – but adding something to the readme might be helpful for others :)

**Comment by andylolz** [comment]
> adding something to the readme might be helpful for others :)

Kk good plan.

If it’s okay, I’ll reword the title of this issue to that effect.

**Comment by andylolz** [comment]
Hopefully fixed in 81c2357.
